# Generated by Django 4.2.6 on 2024-01-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0004_alter_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
