# Generated by Django 4.2.6 on 2024-02-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0005_candidate_total_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
